runtime: nodejs18

service: lexin-frontend

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  NEXT_PUBLIC_BACKEND_SERVICE_BASE_URL: https://backend-dot-lexin-ta.et.r.appspot.com 