name: Deploy to Cloud Run

on:
  push:
    branches:
      - staging  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: lexin-ta

      - name: Build and push Docker image to Container Registry
        run: |
          gcloud builds submit --tag gcr.io/lexin-ta/lexin-frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy lexin-frontend \
            --image gcr.io/lexin-ta/lexin-frontend \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars NEXT_PUBLIC_BACKEND_SERVICE_BASE_URL=https://backend-dot-lexin-ta.et.r.appspot.com
