name: Deploy to Google App Engine (GAE)

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Environment Variables to app yaml
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        with:
          app_yaml_path: "app.yaml"
        env:
          NEXT_PUBLIC_BACKEND_SERVICE_BASE_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_SERVICE_BASE_URL }}

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next Project
        run: pnpm build

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml --quiet