name: Deploy to VM

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: raditskc/lexin-frontend:latest

    - name: SSH to VM and run deploy.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
        SSH_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
        VM_HOST: ${{ secrets.VM_HOST }}  
        VM_USER: ${{ secrets.VM_USER }}  
        VM_PASSWORD: ${{ secrets.VM_PASSWORD }}  
        SSH_TUNNEL_HOST: ${{ secrets.SSH_TUNNEL_HOST }}
        SSH_TUNNEL_USERNAME: ${{ secrets.SSH_TUNNEL_USERNAME }}
        SSH_TUNNEL_PORT: ${{ secrets.SSH_TUNNEL_PORT }}
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa

        eval "$(ssh-agent -s)"
        
        expect << EOF
          spawn ssh-add id_rsa
          expect "Enter passphrase for id_rsa:"
          send "$SSH_PASSPHRASE\r"
          expect eof
        EOF
        
        sshpass -p "$VM_PASSWORD" ssh -i id_rsa -o StrictHostKeyChecking=no -J $SSH_TUNNEL_USERNAME@$SSH_TUNNEL_HOST:$SSH_TUNNEL_PORT $VM_USER@$VM_IP "bash -s" < ~/lexin-frontend/deploy.sh
